sudo: required
language: go
go: 
  - 1.14.2

services:
  - docker

jobs:
  include:
    - stage: "Tests and Linting"
      name: "Linting"
      script: go vet ./...
      name: "Unit Tests"
      script: go test -v ./...
    - stage: "Build and Push Docker Image"
      name: "Build and Push Docker Image"
      script:
      - docker build -t jaskaransarkaria/timer-server:"$TRAVIS_TAG" .
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker push jaskaransarkaria/timer-server:"$TRAVIS_TAG"
    - stage: Deploy to Kubernetes
      before_install:
        - openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv -in client-secret.json.enc -out client-secret.json -d
        - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
      script: 
      - kubectl version --client
      - kubectl config view
      - gcloud auth activate-service-account travis-deployer@jobspeed.iam.gserviceaccount.com --key-file=client-secret.json
      - gcloud container clusters get-credentials jobspeed-production --zone europe-west2-a --project jobspeed
      - kubectl get pods
      # next step is to deploy to kubernetes

stages:
  - Tests and Linting
  - Deploy to Kubernetes
  - name: "Build and Push Docker Image"
    if: tag IS present








