language: go
go: 
  - 1.14.2

services:
  - docker

jobs:
  include:
    - stage: "Tests and Linting"
      name: "Linting"
      script: go vet ./...
      name: "Unit Tests"
      script: go test -v ./...
    - stage: "Build Docker Image"
      name: "Build and Push docker image"
      script: |
        # echo "$TRAVIS_TAG"
        echo "$TRAVIS_BRANCH"
        docker build -t jaskaransarkaria/timer-server:"$TRAVIS_BRANCH" .
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
        docker push jaskaransarkaria/timer-server:"$TRAVIS_BRANCH"

stages:
  - Tests and Linting
  - name: "Build and Push Docker Image"
    if: tag IS present
