sudo: required
language: go
go: 
  - 1.14.2

services:
  - docker

jobs:
  include:
    - stage: "Tests and Linting"
      name: "Linting"
      script: go vet ./...
      name: "Unit Tests"
      script: go test -v ./...
    - stage: "Build and Push Docker Image"
      name: "Build and Push Docker Image"
      script:
      - docker build -t jaskaransarkaria/timer-server:"$TRAVIS_TAG" .
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker push jaskaransarkaria/timer-server:"$TRAVIS_TAG"
      - stage: Deploy to Kubernetes
      env:
        global:
          - CLOUDSDK_CORE_DISABLE_PROMPTS=1
      before_install:
        - curl https://sdk.cloud.google.com | bash > /dev/null
        - source $HOME/google-cloud-sdk/path.bash.inc
        - gcloud components install kubectl
      script: kubectl version

      # next step is to deploy to kubernetes

stages:
  - Deploy to Kubernetes
  # - Tests and Linting
  # - name: "Build and Push Docker Image"
  #   if: tag IS present



