sudo: required
language: go
go: 
  - 1.14.2

services:
  - docker

jobs:
  include:
    - stage: "Tests and Linting"
      name: "Linting"
      script: go vet ./...
      name: "Unit Tests"
      script: go test -v ./...
    - stage: "Build and Push Docker Image"
      name: "Build and Push Docker Image"
      script:
      - docker build -t jaskaransarkaria/timer-server:"$TRAVIS_TAG" .
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker push jaskaransarkaria/timer-server:"$TRAVIS_TAG"
    - stage: Deploy to Kubernetes
      before_install:
        - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
      script: kubectl version

      # next step is to deploy to kubernetes

stages:
  - Deploy to Kubernetes
  # - Tests and Linting
  # - name: "Build and Push Docker Image"
  #   if: tag IS present



