language: go
go: 
  - 1.14.2

before_script:
  - go vet ./...

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: go test -v ./...
    - stage: "Build and Push Image"
      name: "Build docker image"
      script: echo "building..."

stages:
  - Tests
  - Build and Push
