language: go
go: 
  - 1.14.2

services:
  - docker

jobs:
  include:
    - stage: "Tests and Linting"
      name: "Linting"
      script: go vet ./...
      name: "Unit Tests"
      script: go test -v ./...
    - stage: "Build and Push Docker Image"
      name: "Build and Push Docker Image"
      script:
      - docker build -t jaskaransarkaria/timer-server:test .
      - echo "$DOCKER_PASSWORD"
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker push jaskaransarkaria/timer-server:test
      # next step is to deploy to kubernetes

stages:
  - Tests and Linting
  - name: "Build and Push Docker Image"
    # if: tag IS present
