language: go
go: 
  - 1.14.2

services:
  - docker

jobs:
  include:
    - stage: "Tests and Linting"
      name: "Linting"
      script: go vet ./...
      name: "Unit Tests"
      script: go test -v ./...
    - stage: "Build and Push Image"
      name: "Build docker image"
      script: docker build -t travis-build .

stages:
  - Tests and Linting
  - name: Build and Push
      # if: branch = master
